"""add_ai_events_table

Revision ID: 905390c5a2aa
Revises: 3b53dc2e5aab
Create Date: 2025-12-31 17:28:34.033644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '905390c5a2aa'
down_revision: Union[str, None] = '3b53dc2e5aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frame_id', sa.Integer(), nullable=True),
    sa.Column('detections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['devices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_events_camera_id'), 'ai_events', ['camera_id'], unique=False)
    op.create_index('ix_ai_events_camera_model', 'ai_events', ['camera_id', 'model_id'], unique=False)
    op.create_index('ix_ai_events_camera_timestamp', 'ai_events', ['camera_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ai_events_model_id'), 'ai_events', ['model_id'], unique=False)
    op.create_index('ix_ai_events_model_timestamp', 'ai_events', ['model_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_ai_events_timestamp'), 'ai_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_events_timestamp'), table_name='ai_events')
    op.drop_index('ix_ai_events_model_timestamp', table_name='ai_events')
    op.drop_index(op.f('ix_ai_events_model_id'), table_name='ai_events')
    op.drop_index('ix_ai_events_camera_timestamp', table_name='ai_events')
    op.drop_index('ix_ai_events_camera_model', table_name='ai_events')
    op.drop_index(op.f('ix_ai_events_camera_id'), table_name='ai_events')
    op.drop_table('ai_events')
    # ### end Alembic commands ###


